---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enzol.
--- DateTime: 21/10/2022 18:33
---

fx_version 'cerulean'
game 'gta5'

client_script {
'client/*.lua',
'build/js/client/commands.js',
'build/js/client/ui.js'
}

server_script {
    'build/js/server/server.js'
}

ui_page "index.html"

files {
    "index.html",
    "style.css",
    "build/js/client/commands.js",
    "build/js/client/ui.js",
    'build/js/server/server.js'
}